### PR TITLE
REPORT FROM CSV AND FROM API

### PR DESCRIPTION
**Pull request by Gooowan**
It was so exciting to write this feature and I am glad to have this possibility to merge this exciting code with no less exciting repo. THNK GD I BRTH TNGHT

### CODE REVIEW

**Comment by LazarenkoDmytro** [comment]
I like this project because of good CSV file parse. Also, the coding style follows the standards. I am excited with the professional API usage and understandable comments in each block. My standing ovation

**Comment by DavidBakalov21** [comment]
Good wook

**Comment by LightningMcMeth** [comment]
Very good code. I screenshot and copied it so I can use it as my own, like a true programmer.
Professional level work, if I was hiring software engineers, I would hire you.
10/10 👍👍💀

**Comment by LevkoBe** [comment]
Very nice code! Nothing superfluous, instead clear and understandable!

**Pull request closed without merging**
